// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Simplewallethq/simple-wallet-tg-bot/tg-bot/ent/predicate"
	"github.com/Simplewallethq/simple-wallet-tg-bot/tg-bot/ent/privatekeys"
)

// PrivateKeysDelete is the builder for deleting a PrivateKeys entity.
type PrivateKeysDelete struct {
	config
	hooks    []Hook
	mutation *PrivateKeysMutation
}

// Where appends a list predicates to the PrivateKeysDelete builder.
func (pkd *PrivateKeysDelete) Where(ps ...predicate.PrivateKeys) *PrivateKeysDelete {
	pkd.mutation.Where(ps...)
	return pkd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pkd *PrivateKeysDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, pkd.sqlExec, pkd.mutation, pkd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (pkd *PrivateKeysDelete) ExecX(ctx context.Context) int {
	n, err := pkd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pkd *PrivateKeysDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(privatekeys.Table, sqlgraph.NewFieldSpec(privatekeys.FieldID, field.TypeInt))
	if ps := pkd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pkd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	pkd.mutation.done = true
	return affected, err
}

// PrivateKeysDeleteOne is the builder for deleting a single PrivateKeys entity.
type PrivateKeysDeleteOne struct {
	pkd *PrivateKeysDelete
}

// Where appends a list predicates to the PrivateKeysDelete builder.
func (pkdo *PrivateKeysDeleteOne) Where(ps ...predicate.PrivateKeys) *PrivateKeysDeleteOne {
	pkdo.pkd.mutation.Where(ps...)
	return pkdo
}

// Exec executes the deletion query.
func (pkdo *PrivateKeysDeleteOne) Exec(ctx context.Context) error {
	n, err := pkdo.pkd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{privatekeys.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pkdo *PrivateKeysDeleteOne) ExecX(ctx context.Context) {
	if err := pkdo.Exec(ctx); err != nil {
		panic(err)
	}
}
