// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AdressBook is the predicate function for adressbook builders.
type AdressBook func(*sql.Selector)

// Balances is the predicate function for balances builders.
type Balances func(*sql.Selector)

// Delegates is the predicate function for delegates builders.
type Delegates func(*sql.Selector)

// Invoice is the predicate function for invoice builders.
type Invoice func(*sql.Selector)

// Invoices_payments is the predicate function for invoices_payments builders.
type Invoices_payments func(*sql.Selector)

// PrivateKeys is the predicate function for privatekeys builders.
type PrivateKeys func(*sql.Selector)

// RecentInvoices is the predicate function for recentinvoices builders.
type RecentInvoices func(*sql.Selector)

// RewardsData is the predicate function for rewardsdata builders.
type RewardsData func(*sql.Selector)

// Settings is the predicate function for settings builders.
type Settings func(*sql.Selector)

// Swaps is the predicate function for swaps builders.
type Swaps func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)

// Transfers is the predicate function for transfers builders.
type Transfers func(*sql.Selector)

// Undelegates is the predicate function for undelegates builders.
type Undelegates func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserState is the predicate function for userstate builders.
type UserState func(*sql.Selector)

// Validators is the predicate function for validators builders.
type Validators func(*sql.Selector)
