-- Drop index "settings_last_scanned_block_notificator_key" from table: "settings"
DROP INDEX "settings_last_scanned_block_notificator_key";
-- Modify "settings" table
ALTER TABLE "settings" ALTER COLUMN "last_scanned_block_notificator" DROP NOT NULL, ADD COLUMN "last_scanned_era_validators" bigint NULL;
-- Create "validators" table
CREATE TABLE "validators" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "address" character varying NOT NULL, "name" character varying NULL, "fee" smallint NULL, "delegators" bigint NULL, "active" boolean NULL, PRIMARY KEY ("id"));
-- Create index "validators_address_key" to table: "validators"
CREATE UNIQUE INDEX "validators_address_key" ON "validators" ("address");
-- Create "delegates" table
CREATE TABLE "delegates" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "delegator" character varying NOT NULL, "validator" character varying NULL, "name" character varying NULL, "user_balance" character varying NULL, "amount" character varying NULL, "created_at" timestamptz NULL, "status" character varying NULL, "deploy" character varying NULL, "user_delegates" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "delegates_users_delegates" FOREIGN KEY ("user_delegates") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
