-- Modify "transfers" table
ALTER TABLE "transfers" ALTER COLUMN "to_pubkey" DROP NOT NULL, ALTER COLUMN "name" DROP NOT NULL, ALTER COLUMN "sender_balance" DROP NOT NULL, ALTER COLUMN "amount" DROP NOT NULL, ALTER COLUMN "memo_id" DROP NOT NULL, ALTER COLUMN "created_at" DROP NOT NULL, ALTER COLUMN "status" DROP NOT NULL, ALTER COLUMN "deploy" DROP NOT NULL;
