-- Modify "users" table
ALTER TABLE "users" DROP COLUMN "privat_key";
-- Create "privat_keys" table
CREATE TABLE "privat_keys" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "privat_key" bytea NULL, "user_private_key" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "privat_keys_users_PrivateKey" FOREIGN KEY ("user_private_key") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create index "privat_keys_user_private_key_key" to table: "privat_keys"
CREATE UNIQUE INDEX "privat_keys_user_private_key_key" ON "privat_keys" ("user_private_key");
