-- Modify "transfers" table
ALTER TABLE "transfers" ADD COLUMN "additional_type" character varying NULL, ADD COLUMN "invoice_id" bigint NULL;
-- Modify "users" table
ALTER TABLE "users" ADD COLUMN "enable_logging" boolean NOT NULL DEFAULT true, ADD COLUMN "registered" boolean NOT NULL DEFAULT false;
-- Create "invoices" table
CREATE TABLE "invoices" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NULL, "address" character varying NULL, "amount" character varying NULL, "currency" character varying NULL, "comment" character varying NULL, "active" boolean NULL, "repeatability" bigint NULL, "paid" bigint NULL, "short" character varying NULL, "memo" bigint NULL, "user_invoices" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "invoices_users_invoices" FOREIGN KEY ("user_invoices") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "invoices_payments" table
CREATE TABLE "invoices_payments" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "from" character varying NULL, "amount" character varying NULL, "correct" boolean NULL, "invoice_payments" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "invoices_payments_invoices_payments" FOREIGN KEY ("invoice_payments") REFERENCES "invoices" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "recent_invoices" table
CREATE TABLE "recent_invoices" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "status" character varying NOT NULL, "invoice_id" bigint NOT NULL, "user_recent_invoices" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "recent_invoices_users_recentInvoices" FOREIGN KEY ("user_recent_invoices") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create index "recent_invoices_invoice_id_key" to table: "recent_invoices"
CREATE UNIQUE INDEX "recent_invoices_invoice_id_key" ON "recent_invoices" ("invoice_id");
-- Create "swaps" table
CREATE TABLE "swaps" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "type" character varying NULL, "to_address" character varying NULL, "from_currency" character varying NULL, "to_currency" character varying NULL, "to_network" character varying NULL, "from_network" character varying NULL, "amount" character varying NULL, "amount_recive" character varying NULL, "refund_address" character varying NULL, "swap_id" character varying NULL, "extra_id" character varying NULL, "invoice_id" bigint NULL, "user_swaps" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "swaps_users_swaps" FOREIGN KEY ("user_swaps") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
